### ISSUE TITLE
Github actions are dying on v2.3.2

### ISSUE THREAD

**Issue by pablohpsilva-forjnetwork** [TenKeyLabs/dappwright#168]
**Describe the bug**
Whenever a github action runs, this errors is being thrown:
Error: browserType.launchPersistentContext: Executable doesn't exist at /home/runner/.cache/ms-playwright/chromium-1055/chrome-linux/chrome

Even if my playwright configuration defines `chromium` by default:
```
projects: [
    {
      name: `chromium`,
      use: { ...devices[`Desktop Chrome`] },
    },
]
```

**To Reproduce**

1. Create a github action like:
```yml
name: E2E Tests
jobs:
  test:
    timeout-minutes: 10
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: "yarn"

      - name: Install dependencies
        if: steps.playwright-cache.outputs.cache-hit != 'true'
        run: yarn install --prefer-offline --frozen-lockfile

      - name: Install playwright
        if: steps.playwright-cache.outputs.cache-hit != 'true'
        run: yarn exec playwright install --with-deps

      - name: Build applications
        run: yarn build

      - name: Start all applications
        run: yarn start&

      - name: Run Playwright tests
        id: e2e-tests
        run: yarn test:e2e
```
3. Make sure github action is run
5. See error

**Logs**

```shell
   1) [chromium] › campaigns/tier-campaign.spec.ts:140:3 › Should connect to metamask and make sure the Mint button is available with the correct text 
 
     Error: browserType.launchPersistentContext: Executable doesn't exist at /home/runner/.cache/ms-playwright/chromium-1055/chrome-linux/chrome
     ╔═════════════════════════════════════════════════════════════════════════╗
     ║ Looks like Playwright Test or Playwright was just installed or updated. ║
     ║ Please run the following command to download new browsers:              ║
     ║                                                                         ║
     ║     npx playwright install                                              ║
     ║                                                                         ║
     ║ <3 Playwright Team                                                      ║
     ╚═════════════════════════════════════════════════════════════════════════╝
 
        at wallets/metamask.ts:8
 
        6 | export const it = test.extend<{ context: BrowserContext; wallet: Dappwright }>({
        7 |   context: async ({}, use) => {
     >  8 |     const [wallet, , context] = await dappwright.bootstrap(``, {
          |                                 ^
 
         at Object.context (/home/runner/work/dapp/__tests__/wallets/metamask.ts:8:[33](https://github.com/dapp/actions/runs/5212578033/jobs/9406362062#step:10:34))
```

**Expected behavior**
It should work with Chromium as well or there should be a way to define the browser and force it to be chrome

**System:**

- OS: github-actions ubuntu
- OS version: latest
- NodeJs version: latest
- dAppwright version: latest
- testing framework: playwright
- testing framework version: latest
